### PR TITLE
Added API use cases to the Flights section

### PR DESCRIPTION
**Pull request by nicoongit**

### CODE REVIEW

**Review by tsolakoua — COMMENTED** [review]
I see some inconsistency in the names of the use cases. The previous ones were starting with a verb such as: Search for a flight, book a hotel etc. but the new ones have API names such as "Airport routes" or "Airport on-time performance". I personally prefer them with the verb as they are more direct of the use case. For example the "Airport routes" could be written as "Get all destinations from airports", something like that (just made it up now) to follow the use-case approach we have defined for the documentation, also is more user friendly for users who are not very familiar with API names.

**Comment by nicoongit** [comment]
> 

Thanks @tsolakoua , I have amended that

**Review by tsolakoua — APPROVED** [review]

**Comment by tsolakoua** [comment]
Thanks a lot @nicoongit , we are good to go after resolving the conflicts :)

**Comment by nicoongit** [comment]
> Thanks a lot @nicoongit , we are good to go after resolving the conflicts :)

Thanks @tsolakoua , resolved!

**Pull request merged**
